apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: kanishksuri/db-app:05
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT

---
kind: Service
apiVersion: v1
metadata:
  name: service-node
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: node
  type: LoadBalancer
